-- Market Memory V0: thesis -> assumptions -> evidence -> immutable snapshots
-- Run this once in the Supabase SQL editor.

create table if not exists public.theses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_symbol text not null,
  asset_name text,
  asset_type text not null check (asset_type in ('crypto', 'stock')),
  backend_id text,
  expected_outcome text not null,
  reasoning text not null,
  invalidation_condition text not null,
  timeframe text,
  confidence smallint not null default 5 check (confidence between 1 and 10),
  status text not null default 'active' check (status in ('draft', 'active', 'weakened', 'broken', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thesis_assumptions (
  id bigint generated by default as identity primary key,
  thesis_id bigint not null references public.theses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  statement text not null,
  status text not null default 'unknown' check (status in ('unknown', 'strengthening', 'stable', 'weakening', 'broken')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.thesis_evidence (
  id bigint generated by default as identity primary key,
  thesis_id bigint not null references public.theses(id) on delete cascade,
  assumption_id bigint references public.thesis_assumptions(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  direction text not null check (direction in ('supports', 'contradicts', 'neutral')),
  summary text not null,
  source_url text,
  source_title text,
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.thesis_snapshots (
  id bigint generated by default as identity primary key,
  thesis_id bigint not null references public.theses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  thesis_payload jsonb not null,
  market_payload jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists theses_user_created_idx on public.theses(user_id, created_at desc);
create index if not exists theses_user_asset_idx on public.theses(user_id, asset_symbol);
create index if not exists assumptions_thesis_idx on public.thesis_assumptions(thesis_id);
create index if not exists evidence_thesis_idx on public.thesis_evidence(thesis_id, observed_at desc);
create index if not exists snapshots_thesis_idx on public.thesis_snapshots(thesis_id, created_at desc);

alter table public.theses enable row level security;
alter table public.thesis_assumptions enable row level security;
alter table public.thesis_evidence enable row level security;
alter table public.thesis_snapshots enable row level security;

drop policy if exists "theses_owner_all" on public.theses;
create policy "theses_owner_all" on public.theses
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "assumptions_owner_all" on public.thesis_assumptions;
create policy "assumptions_owner_all" on public.thesis_assumptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "evidence_owner_all" on public.thesis_evidence;
create policy "evidence_owner_all" on public.thesis_evidence
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "snapshots_owner_select_insert" on public.thesis_snapshots;
drop policy if exists "snapshots_owner_insert" on public.thesis_snapshots;
create policy "snapshots_owner_select_insert" on public.thesis_snapshots
  for select using (auth.uid() = user_id);
create policy "snapshots_owner_insert" on public.thesis_snapshots
  for insert with check (auth.uid() = user_id);

create or replace function public.prevent_thesis_snapshot_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'thesis_snapshots are immutable';
end;
$$;

drop trigger if exists thesis_snapshots_immutable_update on public.thesis_snapshots;
create trigger thesis_snapshots_immutable_update
before update on public.thesis_snapshots
for each row execute function public.prevent_thesis_snapshot_mutation();

drop trigger if exists thesis_snapshots_immutable_delete on public.thesis_snapshots;
create trigger thesis_snapshots_immutable_delete
before delete on public.thesis_snapshots
for each row execute function public.prevent_thesis_snapshot_mutation();
