-- Market Memory core: observations and immutable market snapshots

create table if not exists public.market_observations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    asset_name text,
    asset_type text not null check (asset_type in ('crypto', 'stock')),
    backend_id text,
    observation text not null check (char_length(trim(observation)) > 0),
    price numeric,
    created_at timestamptz not null default now()
);

create index if not exists market_observations_user_created_idx
    on public.market_observations(user_id, created_at desc);
create index if not exists market_observations_user_symbol_idx
    on public.market_observations(user_id, symbol, created_at desc);

alter table public.market_observations enable row level security;

drop policy if exists "Users manage own market observations" on public.market_observations;
create policy "Users manage own market observations"
    on public.market_observations for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create table if not exists public.market_snapshots (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    symbol text not null,
    asset_name text,
    asset_type text not null check (asset_type in ('crypto', 'stock')),
    backend_id text,
    price numeric,
    note text,
    market_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists market_snapshots_user_created_idx
    on public.market_snapshots(user_id, created_at desc);
create index if not exists market_snapshots_user_symbol_idx
    on public.market_snapshots(user_id, symbol, created_at desc);

alter table public.market_snapshots enable row level security;

drop policy if exists "Users read own market snapshots" on public.market_snapshots;
create policy "Users read own market snapshots"
    on public.market_snapshots for select
    using (auth.uid() = user_id);

drop policy if exists "Users create own market snapshots" on public.market_snapshots;
create policy "Users create own market snapshots"
    on public.market_snapshots for insert
    with check (auth.uid() = user_id);

-- A snapshot is historical evidence. It must never be rewritten or deleted.
create or replace function public.prevent_market_snapshot_mutation()
returns trigger language plpgsql as $$
begin
    raise exception 'Market snapshots are immutable';
end;
$$;

drop trigger if exists market_snapshots_immutable_update on public.market_snapshots;
create trigger market_snapshots_immutable_update
before update on public.market_snapshots
for each row execute function public.prevent_market_snapshot_mutation();

drop trigger if exists market_snapshots_immutable_delete on public.market_snapshots;
create trigger market_snapshots_immutable_delete
before delete on public.market_snapshots
for each row execute function public.prevent_market_snapshot_mutation();
